--------------------------------------------------------
--  File created - Monday-October-24-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ASOCIERI
--------------------------------------------------------

  CREATE TABLE "STATIA08"."ASOCIERI" 
   (	"ID_ASOC" NUMBER(38,0), 
	"ID_PRODUS" NUMBER(38,0), 
	"ID_PROPRIETATE" NUMBER(38,0), 
	"VALOARE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CATEGORIE
--------------------------------------------------------

  CREATE TABLE "STATIA08"."CATEGORIE" 
   (	"ID_CATEGORIE" NUMBER(38,0), 
	"NUME" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMENZI
--------------------------------------------------------

  CREATE TABLE "STATIA08"."COMENZI" 
   (	"ID_CUMPARATOR" NUMBER(38,0), 
	"ID_PRODUS" NUMBER(38,0), 
	"ID_COMANDA" NUMBER(38,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CUMPARATORI
--------------------------------------------------------

  CREATE TABLE "STATIA08"."CUMPARATORI" 
   (	"ID_CUMPARATOR" NUMBER(38,0), 
	"NUME" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUSE
--------------------------------------------------------

  CREATE TABLE "STATIA08"."PRODUSE" 
   (	"ID_PRODUS" NUMBER(38,0), 
	"NUME_PRODUS" VARCHAR2(20 BYTE), 
	"ID_CATEGORIE" NUMBER(38,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROPRIETATI
--------------------------------------------------------

  CREATE TABLE "STATIA08"."PROPRIETATI" 
   (	"ID_PROPRIETATE" NUMBER(38,0), 
	"PROPRIETATE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
