CREATE TABLE TEAMS (  TEAM_ID INT constraint pk_teamid primary key, TEAM_NAME VARCHAR(20)  );
CREATE TABLE RESULTS( 
TEAM_ID1 INT, constraint FK_TEAMID1 FOREIGN KEY(TEAM_ID1) REFERENCES TEAMS(TEAM_ID),
TEAM_ID2 INT, constraint FK_TEAMID2 FOREIGN KEY(TEAM_ID2) REFERENCES TEAMS(TEAM_ID),
  Goals_Team1 INT,
  Goals_Team2 INT, 
  UNIQUE(TEAM_ID1,TEAM_ID2)
 );

INSERT INTO TEAMS(TEAM_ID,TEAM_NAME) VALUES('1','Real Madrid');
INSERT INTO TEAMS(TEAM_ID,TEAM_NAME) VALUES('2','Barcelona');
INSERT INTO TEAMS(TEAM_ID,TEAM_NAME) VALUES('3','Dinamita');
INSERT INTO TEAMS(TEAM_ID,TEAM_NAME) VALUES('4','Bomba');
INSERT INTO TEAMS(TEAM_ID,TEAM_NAME) VALUES('5','Portocala');
INSERT INTO TEAMS(TEAM_ID,TEAM_NAME) VALUES('6','Cianura');

INSERT INTO RESULTS(TEAM_ID1,TEAM_ID2,Goals_Team1,Goals_Team2) VALUES ('1','2','1','3');
INSERT INTO RESULTS(TEAM_ID1,TEAM_ID2,Goals_Team1,Goals_Team2) VALUES ('2','1','2','1');

INSERT INTO RESULTS(TEAM_ID1,TEAM_ID2,Goals_Team1,Goals_Team2) VALUES ('3','4','1','1');
INSERT INTO RESULTS(TEAM_ID1,TEAM_ID2,Goals_Team1,Goals_Team2) VALUES ('4','3','0','1');

INSERT INTO RESULTS(TEAM_ID1,TEAM_ID2,Goals_Team1,Goals_Team2) VALUES ('5','6','5','5');
INSERT INTO RESULTS(TEAM_ID1,TEAM_ID2,Goals_Team1,Goals_Team2) VALUES ('6','5','0','0');


INSERT INTO RESULTS(TEAM_ID1,TEAM_ID2,Goals_Team1,Goals_Team2) VALUES ('1','5','2','1');
INSERT INTO RESULTS(TEAM_ID1,TEAM_ID2,Goals_Team1,Goals_Team2) VALUES ('5','1','1','1');
INSERT INTO RESULTS(TEAM_ID1,TEAM_ID2,Goals_Team1,Goals_Team2) VALUES ('2','4','3','1');
INSERT INTO RESULTS(TEAM_ID1,TEAM_ID2,Goals_Team1,Goals_Team2) VALUES ('4','2','1','2');



CREATE VIEW CLASAMENT ("TEAMS", "POINTS") AS 
  SELECT T.TEAM_NAME AS TEAMS,
       SUM(
         CASE
                WHEN  T.TEAM_ID = R.TEAM_ID1 THEN  DECODE(SIGN(R.Goals_Team1 - R.Goals_Team2), 0, 1, 1, 3)
                WHEN  T.TEAM_ID = R.TEAM_ID2 THEN DECODE(SIGN(R.Goals_Team1 - R.Goals_Team2), 0, 1, -1, 3) 
         END) AS POINTS
FROM 
    TEAMS T, 
    RESULTS R 
GROUP BY T.TEAM_NAME
ORDER BY POINTS DESC; 