CREATE OR REPLACE PROCEDURE "PRINT_MSG"
( MSG IN VARCHAR2) AS
BEGIN
 DBMS_OUTPUT.put_line (MSG);
END PRINT_MSG;
/
CREATE OR REPLACE PROCEDURE "MKDIR"
(
  FOLDER_ID IN NUMBER,
  FOLDER_NAME IN VARCHAR2,
  PARENT_ID IN NUMBER
) AS

NO_UNIQ EXCEPTION;
NO_FOLDER EXCEPTION;
PRAGMA EXCEPTION_INIT(NO_UNIQ,-1);
PRAGMA EXCEPTION_INIT(NO_FOLDER,-2291);
BEGIN
  INSERT INTO FOLDERS(FOLDER_ID,FOLDER_NAME,PARENT_ID) VALUES (FOLDER_ID,FOLDER_NAME,PARENT_ID);
EXCEPTION
  WHEN NO_UNIQ THEN
    PRINT_MSG('PLEASE MAKE SURE THAT FOLDER_ID AND FOLDER_NAME BOTH ARE UNIQE');
  WHEN NO_FOLDER THEN
    PRINT_MSG('PLEASE MAKE SURE THAT THE ROOT FOLDER EXISTS BEFORE CREATING A NEW ONE');
END MKDIR;
/

CREATE OR REPLACE PROCEDURE "MKFILE"
(
  FILE_ID IN NUMBER,
  FILE_NAME IN VARCHAR2,
  FOLDER_ID IN NUMBER
  ) AS
  BEGIN
  INSERT INTO FILES(FILE_ID,FILE_NAME,FOLDER_ID,FILE_CONTENT) VALUES (FILE_ID,FILE_NAME,FOLDER_ID,'DEFAULT CONTENT');
  END MKFILE;
  /

CREATE OR REPLACE PROCEDURE "DEL"
(FOLDER_ID IN NUMBER)
AS
BEGIN
  DELETE FROM FOLDERS WHERE FOLDERS.FOLDER_ID = FOLDER_ID;
  DELETE FROM FILES WHERE FILES.FOLDER_ID = FOLDER_ID;
END DEL;
/

CREATE OR REPLACE PROCEDURE "LD"
(
  PARENT_ID IN NUMBER
)AS
BEGIN
  FOR REC IN (SELECT * FROM FOLDERS) LOOP
   IF(REC.PARENT_ID = PARENT_ID) 
    THEN
      DBMS_OUTPUT.put_line (REC.FOLDER_NAME);
    END IF;
  END LOOP;
END;
/

CREATE OR REPLACE PROCEDURE "LF"
(
PARENT_ID IN NUMBER,
FILE_NAME IN VARCHAR2
)AS
BEGIN
FOR REC IN (SELECT * FROM FILES) LOOP
  IF(REC.FOLDER_ID=PARENT_ID AND REC.FILE_NAME = FILE_NAME)
  THEN
  PRINT_MSG(REC.FILE_CONTENT);
  END IF;
END LOOP;
END LF;
/
CREATE OR REPLACE PROCEDURE "CD"
(
  PARENT_ID IN OUT NUMBER,
  FOLDER_NAME IN VARCHAR2
)AS
NO_SUCH_DIRECTORY EXCEPTION;
BEGIN 
  IF  (PARENT_ID < 0) THEN
   RAISE NO_SUCH_DIRECTORY;
  END IF;
  IF(FOLDER_NAME = '..') THEN
    SELECT FOLD.FOLDER_ID INTO PARENT_ID FROM FOLDERS FOLD WHERE FOLD.FOLDER_ID = PARENT_ID;
  ELSE
    SELECT FOLD.FOLDER_ID INTO PARENT_ID FROM FOLDERS FOLD WHERE FOLD.FOLDER_ID = PARENT_ID AND FOLD.FOLDER_NAME = FOLDER_NAME;
  END IF;
EXCEPTION 
  WHEN NO_SUCH_DIRECTORY THEN
    PRINT_MSG('NO SUCH DIRECTORY AVAILABLE');
END CD;
/

CREATE OR REPLACE PROCEDURE "WRITE_FILE"
(
  FILE_ID IN NUMBER,
  FILECONTENT IN VARCHAR2
)AS
BEGIN
  UPDATE FILES 
  SET FILES.FILE_CONTENT=FILECONTENT
  WHERE FILES.FILE_ID = FILE_ID;
END WRITE_FILE;
/


