
  CREATE TABLE "ST_02"."FOLDERS" 
   (	"FOLDER_ID" NUMBER NOT NULL ENABLE, 
	"FOLDER_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PARENT_ID" NUMBER, 
	 CONSTRAINT "FOLDERS_PK" PRIMARY KEY ("FOLDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FOLDERS_FK1" FOREIGN KEY ("PARENT_ID")
	  REFERENCES "ST_02"."FOLDERS" ("FOLDER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  

  CREATE TABLE "ST_02"."FILES" 
   (	"FILE_ID" NUMBER NOT NULL ENABLE, 
	"FILE_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"FOLDER_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "FILES_PK" PRIMARY KEY ("FILE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FILES_FK1" FOREIGN KEY ("FOLDER_ID")
	  REFERENCES "ST_02"."FOLDERS" ("FOLDER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;